export const SearchedNewsActionTypes = {
  GET_SEARCHED_NEWS_REQUEST: "GET_SEARCHED_NEWS_REQUEST",
  GET_SEARCHED_NEWS_SUCCESS: "GET_SEARCHED_NEWS_SUCCESS",
  GET_MORE_SEARCHED_NEWS: "GET_MORE_SEARCHED_NEWS",
  GET_SEARCHED_NEWS_FAILURE: "GET_SEARCHED_NEWS_FAILURE",
};
