export const NewsActionTypes = {
  GET_NEWS_REQUEST: "GET_NEWS_REQUEST",
  GET_NEWS_SUCCESS: "GET_NEWS_SUCCESS",
  GET_MORE_NEWS: "GET_MORE_NEWS",
  GET_SEARCHED_NEWS_SUCCESS: "GET_SEARCHED_NEWS_SUCCESS",
  GET_NEWS_FAILURE: "GET_NEWS_FAILURE",
};
