export const NewsActionTypes = {
  GET_NEWS_REQUEST: "GET_NEWS_REQUEST",
  GET_NEWS_SUCCESS: "GET_NEWS_SUCCESS",
  GET_MORE_NEWS: "GET_MORE_NEWS",
  GET_NEWS_FAILURE: "GET_NEWS_FAILURE",
  SET_QUERY: "SET_QUERY",
  SET_SORT_BY: "SET_SORT_BY",
};
